Добавляет разметку главной страницы
htmlacademy-adaptive/1826607-cat-energy-25 pull request #2
Opened 2022-04-03 07:24 UTC by andreevvaleksandr

2022-04-09 11:44 UTC, GennadiyM requested changes

2022-04-09 11:44 UTC, GennadiyM commented on source/catalog.html
> +  <body class="page-body">
page__body

2022-04-09 11:44 UTC, GennadiyM commented on source/form.html
> +  <body class="page-body">
page__body

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +        <button class="header-nav__toggle" type="button" aria-label="Открыть меню"></button>
да почему он в nav то, никакого отношения к nav это не имеет. он графически тут только привязан

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +          <button class="promo__btn btn">Подобрать программу</button>
a href nowhere

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +        <button class="header-nav__toggle" type="button" aria-label="Открыть меню"></button>
а откуда появилось nav в header-NAV?

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +        <section class="product__features features">
а что за product__features

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +              <button class="features__btn btn">Каталог slim</button>
ссылка

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +              <button class="features__btn btn">Каталог pro</button>
сслыка

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +        <section class="about">
здесь about

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +          <h2 class="product-about__title">Как это работает</h2>
а здесь product-about

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +              Функциональное питание содержит только полезные питательные вещества.
почему текст на след строку перенес?

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +            <li class="product-about__item">
почему модификаторы им не проставил? у них разные картинки будут

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +      <div class="footer-wrapper">
может page__wrapper footer__wrapper

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +              <p class="adress__city">Санкт-Петербург</p>
да почему два разных параграфа? потому что на разных строках? дизайн не влияет на семантику, никогда

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +            <div class="offer__adress adress">
зачем здесь див?

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +        <div class="footer__contacts"></div>
а это что?

2022-04-09 11:44 UTC, GennadiyM commented on source/index.html
> +          <a class="social__logo" href="#nowhere">
а почему nowhere а не index?

2022-04-10 06:14 UTC, andreevvaleksandr commented on source/index.html
> +        <button class="header-nav__toggle" type="button" aria-label="Открыть меню"></button>
_"а откуда появилось nav в header-NAV?"_ - Header использовал для контейнера навигации

2022-04-10 06:17 UTC, andreevvaleksandr commented on source/index.html
> +        <section class="product__features features">
Тут отображаю преимущества самого продукта

2022-04-10 06:23 UTC, andreevvaleksandr commented on source/index.html
> +              Функциональное питание содержит только полезные питательные вещества.
Formatter перенес: https://10015.io/tools/html-formatter

2022-04-10 11:01 UTC, GennadiyM requested changes

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +              Функциональное питание содержит только полезные питательные вещества.
ну и зачем ты им пользуешься? Или тебе нравится туда сюда одну и туже домашку сдавать. Критерий никто не отменял и проверяющему может оказаться не до твоего форматера

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +          <p class="legal__text">HTML Academy</p>
А что этот текст не ссылка?

2022-04-10 11:01 UTC, GennadiyM commented on source/catalog.html
> +  <body class="page-body">
page__body дубль 2.

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +  <body class="page">
page__body

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
>  <html lang="ru">
page

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +      <div class="page-wrapper">
page__wrapper

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +      <div class="footer__wrapper">
page__wrapper footer__wrapper

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +        </div>
где то в этом блоке еще page__wrapper нужно будет дописать какому-то блоку (более вероятно) или добавить обертку (менее вереоятно)

2022-04-10 11:01 UTC, GennadiyM commented on source/index.html
> +          </div>
Вот этот блок в page__wrpapper  не подходит, он должен иметь page__wrapper внутри себя

2022-04-10 14:02 UTC, andreevvaleksandr commented on source/index.html
> +  <body class="page">
Почему не можем оставить page?

2022-04-10 23:29 UTC, merged